# Generated by Django 3.1.1 on 2020-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_update', models.IntegerField()),
                ('subscribers', models.TextField(default='[]')),
                ('is_facebook', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15)),
                ('pages', models.JSONField(null=True)),
            ],
        ),
    ]
