# Generated by Django 4.0.4 on 2022-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_update', models.BigIntegerField(blank=True, null=True)),
                ('subscribers', models.ManyToManyField(related_name='subscriptions', to='fbpages.telegramuser')),
            ],
        ),
    ]
